### ISSUE TITLE
Actividad 7 Reconocimiento 

### ISSUE THREAD

**Issue by FedericoVictorianoSierra** [SistemasTecTlaxiaco/cs-promastergamer#1]

**Comment by FedericoVictorianoSierra** [comment]
[Actividad 7 MultiTargets.pdf](https://github.com/SistemasTecTlaxiaco/cs-promastergamer/files/15169526/Actividad.7.MultiTargets.pdf)

**Comment by NoeliaGlez** [comment]
20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
